version: '3.7'
services:
  back:
    image: back-main
    hostname: back
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
 